### PR TITLE
EKP Network-migration changed domain names

### PR DESCRIPTION
**Pull request by Fra-nk**
-> new default config file
- keep old file as fallback for a few versions, until everything is migrated

### CODE REVIEW

**Comment by Fra-nk** [comment]
Apparently you (accidentally?) deleted this commit by pushing to the master branch with force mode?

**Comment by FredStober** [comment]
I've moved the commit to the testing branch - pull requests should go that route first

**Comment by Fra-nk** [comment]
While this is a good point which I'll consider in the future, this pull requests includes no coding/functionality, so I think it's an exception to a (good) rule.

It only became necessary because of a network migration, which also changed our machines' host-names.

**Comment by FredStober** [comment]
This change will become part of master with the release candidate.

**Pull request closed without merging**
