### PR TITLE
Bulk submission and delegate usage for cream ce backend

### PR DESCRIPTION
**Pull request by thomas-mueller**
I copied the bulk submission and delegate usage from the GliteWMS backend in wms_glitewms.py into the CreamWMS backend in wms_cream.py. It seems to work.

### CODE REVIEW

**Comment by thomas-mueller** [comment]
There were some mistakes in the submission of jobs using delegates, which should be fixed now. In this sense the PR is OK (to my understanding).

However, all jobs fail (without output in workdir/output/job_x), which is also the case for the state of the testing branch before these changes. I am investigating this (which is difficult without log output), but it is most likely a problem which I did not introduce. Help is very welcome.

**Comment by thomas-mueller** [comment]
Now, job submission and retrieval works for me and I therefore ask for merging this PR. Thanks.

**Comment by FredStober** [comment]
The landscape test shows "9 new and 0 fixed messages." in the overview: https://landscape.io/github/grid-control/grid-control/pulls/

However the service seems to have some problem at the moment, because I get a server error at the moment when trying to access the detailed report. Maybe nothing is wrong but I would like to see the report first ...

You can try to run pylint on the file to see if it finds anything suspicious.

**Comment by thomas-mueller** [comment]
The code is now also tested by other and runs. Let's wait for world nr. 17, where everything will be better.

**Comment by FredStober** [comment]
The whole grid-control source code in testing contains 7 messages (https://landscape.io/github/grid-control/grid-control/1057) - if this pull request introduces 9 new ones, I would be highly suspicious.
Maybe there is overlap, so its just 2 new messages in the end, which would still be a 29% increase...

And yes, testing fixes a few thousand messages in high strictness mode ... leaving 7 :)

**Comment by thomas-mueller** [comment]
Please point (precisely) to these 9 messages (maybe the best would be to copy them here). Thanks.

**Comment by FredStober** [comment]
A quick check gives me these messages:

PYLINT >>>>
************* Module grid_control.backends.wms_cream
C: 22, 0: Line too long (109/100) (line-too-long)
W: 22, 0: Unused safe_write imported from grid_control.utils (unused-import)
W: 22, 0: Unused filter_dict imported from grid_control.utils (unused-import)
W: 26, 0: Unused ifilter imported from python_compat (unused-import)
W: 26, 0: Unused identity imported from python_compat (unused-import)
PEP8 >>>>
wms_cream.py:130:37: E226 missing whitespace around arithmetic operator
                exit_code = proc.status(timeout=20*len(jobs), terminate=True)
                                                  ^
FLAKE8 >>>>
wms_cream.py:22:1: F401 'filter_dict' imported but unused
wms_cream.py:22:1: F401 'safe_write' imported but unused
wms_cream.py:26:1: F401 'identity' imported but unused
wms_cream.py:26:1: F401 'ifilter' imported but unused
wms_cream.py:130:37: E226 missing whitespace around arithmetic operator

Meanwhile I added the server error issue on landscape.io to an existing ticket here: https://github.com/landscapeio/landscape-issues/issues/269

**Comment by FredStober** [comment]
Concerning the line length: the standard actually says 79 chars (https://www.python.org/dev/peps/pep-0008/#maximum-line-length) ... but we loosen this requirement slightly.

**Pull request merged**
