### PR TITLE
Cream CE WMS

### PR DESCRIPTION
**Pull request by thomas-mueller**
First try.

### CODE REVIEW

**Comment by FredStober** [comment]
Hi, a new stable release is coming up - is the CREAM CE ready for this release?

**Comment by thomas-mueller** [comment]
Yes, the CREAM CE is ready for this release.

**Comment by FredStober** [comment]
Ok, I've only minor things - your regex should probably be raw strings r'...'. I think you can fix the final landscape error by using a single tab to indent the continuation:
https://landscape.io/github/artus-analysis/grid-control/2/modules/packages/grid_control/backends/wms_cream.py#L51

**Comment by FredStober** [comment]
Ok - just merge the current master so this pull request can be close. I'll need to rebase the commits properly anyway.

**Comment by thomas-mueller** [comment]
Done. I got a merge conflict when doing `git checkout master; git pull upstream master`, which is not too clear for me why this should happen, as I did not do anything on the master.

**Pull request merged**
